# Generated by Django 3.1.5 on 2021-01-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='static/img/uploads/header', verbose_name='Логотип')),
                ('menu_item1', models.CharField(default='Научим', max_length=30, verbose_name='Пункт меню 1')),
                ('menu_item2', models.CharField(default='Для кого курс', max_length=30, verbose_name='Пункт меню 2')),
                ('menu_item3', models.CharField(default='Что входит', max_length=30, verbose_name='Пункт меню 3')),
                ('menu_item4', models.CharField(default='Автор', max_length=30, verbose_name='Пункт меню 4')),
                ('button_cabinet', models.CharField(max_length=30, verbose_name='Название кнопки в шапке')),
                ('link_button_cabinet', models.CharField(default='#', max_length=300, verbose_name='Название кнопки в шапке')),
                ('h1_block1', models.CharField(max_length=150, verbose_name='Заголовок h1')),
                ('text_block1', models.TextField(default='Мы создали "Реальную школу", чтобы обезопасить подростков от необдуманных финансовых поступков и дать успешные перспективы в будущем', verbose_name='Текст')),
                ('button_1', models.CharField(default='Записаться на курс', max_length=30, verbose_name='Кнопка 1')),
                ('link_button_1', models.CharField(default='#', max_length=300, verbose_name='Ссылка кнопки 1')),
                ('button_2', models.CharField(default='Попробовать бесплатно', max_length=30, verbose_name='Кнопка 2')),
                ('link_button_2', models.CharField(default='#', max_length=300, verbose_name='Ссылка кнопки 2')),
                ('img_block1', models.ImageField(upload_to='static/img/uploads/block1', verbose_name='Картинка')),
                ('h2_block2', models.CharField(default='Интерактивный курс по финансовой грамотности для детей и подростков', max_length=150, verbose_name='Заголовок h2')),
                ('text1_block2', models.TextField(default='С первого урока ученики вовлечены в практические упражнения, которые воспитывают в них', verbose_name='Текст 1')),
                ('speech_cloud1', models.CharField(default='Креативность в поиске нестандартых ходов и решений', max_length=200, verbose_name='Текст речевого облака 1')),
                ('speech_cloud2', models.CharField(default='Ответственное отношение к деньгам ', max_length=200, verbose_name='Текст речевого облака 2')),
                ('speech_cloud3', models.CharField(default='Уважение и чувство ценности к труду', max_length=200, verbose_name='Текст речевого облака 3')),
                ('text2_block2', models.TextField(default='Задача курса "Простые финансы" – не просто рассказать про деньги, а увлечь и дать возможность самостоятельно научится управлять деньгами и зарабатывать.', verbose_name='Текст 2')),
                ('img_block2', models.ImageField(upload_to='static/img/uploads/block2', verbose_name='Картинка')),
                ('h2_block3', models.CharField(default='Для кого этот курс?', max_length=150, verbose_name='Заголовок h2')),
                ('h4_block3', models.CharField(default='Этот курс идеально подходит для подростков 10 - 14 лет независимо от их финансовых навыков.', max_length=200, verbose_name='Подзаголовок (h4)')),
                ('img_col1', models.ImageField(upload_to='static/img/uploads/block3', verbose_name='Картинка (колонка 1)')),
                ('text_col1', models.TextField(default='Если они вообще не вникают в денежные дела семьи и не хотят брать на себя ответственность за личные накопления.', verbose_name='Текст колонки 1')),
                ('img_col2', models.ImageField(upload_to='static/img/uploads/block3', verbose_name='Картинка (колонка 2)')),
                ('text_col2', models.TextField(default='Если они учатся сберегать средства, но ни вы, ни они не знают: а что можно сделать ещё, кроме как завести копилку?', verbose_name='Текст колонки 2')),
                ('img_col3', models.ImageField(upload_to='static/img/uploads/block3', verbose_name='Картинка (колонка 3)')),
                ('text_col3', models.TextField(default='Если они хотят самостоятельно накопить на крупную покупку – или же это важно вам, чтобы они научились ценить дорогие вещи.', verbose_name='Текст колонки 3')),
                ('img_col4', models.ImageField(upload_to='static/img/uploads/block3', verbose_name='Картинка (колонка 4)')),
                ('text_col4', models.TextField(default='И ещё если они активно интересуются – как и где уже сейчас могут заработать деньги, во что вложить и как грамотно распоряжаться финансами.', verbose_name='Текст колонки 4')),
                ('text_block4', models.TextField(default='Чтобы мотивировать детей продолжать обучение, мы выстроили курс с учётомпсихологии подростков. А чего они хотят больше всего?', max_length=150, verbose_name='')),
                ('img_block4', models.ImageField(upload_to='static/img/uploads/block4', verbose_name='Картинка')),
                ('h3_block5', models.CharField(default='Но при этом готовы прислушиваться к мнению авторитетных товарищей: кураторов и сокурскников в "Чате миллионеров".', max_length=250, verbose_name='Заголовок h3')),
                ('button_block5', models.CharField(default='Занять место на конкурсе', max_length=30, verbose_name='Кнопка')),
                ('link_button_block5', models.CharField(default='#', max_length=300, verbose_name='Ссылка кнопки')),
                ('h2_block6', models.CharField(default='Курс "Простые финансы" – это', max_length=150, verbose_name='Заголовок h2')),
                ('digit_col1', models.IntegerField(default=6, verbose_name='Число 1')),
                ('desc_col1', models.TextField(default='недель интенсивных занятий', max_length=120, verbose_name='Текст под числом колонки 1')),
                ('digit_col2', models.IntegerField(default=6, verbose_name='Число 2')),
                ('desc_col2', models.TextField(default='уроков с заданиями в форме видеолекций и квестов', max_length=120, verbose_name='Текст под числом колонки 1')),
                ('digit_col3', models.IntegerField(default=6, verbose_name='Число 3')),
                ('desc_col3', models.TextField(default='минут среднее время прохождения урока', max_length=120, verbose_name='Текст под числом колонки 1')),
                ('digit_col4', models.IntegerField(default=6, verbose_name='Число 4')),
                ('desc_col4', models.TextField(default='онлайн-квеста в Zoom с кураторами и однокурсниками', max_length=120, verbose_name='Текст под числом колонки 1')),
                ('h2_block7', models.CharField(default='Пройдите бесплатный урок', max_length=150, verbose_name='Заголовок h2')),
                ('text_block7', models.TextField(default='Чтобы мотивировать детей продолжать обучение, мы выстроили курс с учётомпсихологии подростков. А чего они хотят больше всего?', max_length=150, verbose_name='')),
            ],
            options={
                'verbose_name': 'Лэндинг',
                'verbose_name_plural': 'Данные по лэндингу',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_name', models.CharField(max_length=50, verbose_name='Имя, фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.TextField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
