# Generated by Django 3.1.5 on 2021-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='digit_col2',
            field=models.IntegerField(default=11, verbose_name='Число 2'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='digit_col3',
            field=models.IntegerField(default=20, verbose_name='Число 3'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='digit_col4',
            field=models.IntegerField(default=2, verbose_name='Число 4'),
        ),
    ]
