# Generated by Django 3.1.5 on 2021-01-17 17:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210117_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='h1_block1',
            field=ckeditor.fields.RichTextField(default='Доверьте ребёнку управлять собственными деньгами', verbose_name='Заголовок h1'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='text2_block2',
            field=ckeditor.fields.RichTextField(default='Задача курса "Простые финансы" – не просто рассказать про деньги, а увлечь и дать возможность самостоятельно научится управлять деньгами и зарабатывать.', verbose_name='Текст 2'),
        ),
    ]
