# Generated by Django 3.1.5 on 2021-01-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210117_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='h1_block1',
            field=models.CharField(max_length=150, verbose_name='Заголовок h1'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='text2_block2',
            field=models.TextField(default='Задача курса "Простые финансы" – не просто рассказать про деньги, а увлечь и дать возможность самостоятельно научится управлять деньгами и зарабатывать.', verbose_name='Текст 2'),
        ),
    ]
