# Generated by Django 3.1.5 on 2021-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210117_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='button_cabinet',
            field=models.CharField(default='Личный кабинет', max_length=30, verbose_name='Название кнопки в шапке'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='h1_block1',
            field=models.CharField(default='Доверьте ребёнку управлять собственными деньгами', max_length=150, verbose_name='Заголовок h1'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='img_block1',
            field=models.FileField(upload_to='static/img/uploads/block1', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='img_block2',
            field=models.FileField(upload_to='static/img/uploads/block2', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='img_block4',
            field=models.FileField(upload_to='static/img/uploads/block4', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='img_col1',
            field=models.FileField(upload_to='static/img/uploads/block3', verbose_name='Картинка (колонка 1)'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='img_col2',
            field=models.FileField(upload_to='static/img/uploads/block3', verbose_name='Картинка (колонка 2)'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='img_col3',
            field=models.FileField(upload_to='static/img/uploads/block3', verbose_name='Картинка (колонка 3)'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='img_col4',
            field=models.FileField(upload_to='static/img/uploads/block3', verbose_name='Картинка (колонка 4)'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='link_button_cabinet',
            field=models.CharField(default='#', max_length=300, verbose_name='Ссылка кнопки в шапке'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='logo',
            field=models.FileField(upload_to='static/img/uploads/header', verbose_name='Логотип'),
        ),
    ]
