# Generated by Django 3.1.5 on 2021-01-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210117_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='h2_block7',
            field=models.CharField(default='Пройдите бесплатный урок', max_length=150, verbose_name='Заголовок h2 в форме'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='text_block4',
            field=models.TextField(default='Чтобы мотивировать детей продолжать обучение, мы выстроили курс с учётомпсихологии подростков. А чего они хотят больше всего?', max_length=150, verbose_name='Текст на голубом фоне'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='text_block7',
            field=models.TextField(max_length=150, verbose_name='Текст в форме'),
        ),
    ]
